#! /usr/bin/env bash

if [ ! -z "$1" ]; then
    # extract the protocol
    protocol="$(echo $1 | grep :// | sed -e's,^\(.*://\).*,\1,g')"

    # remove the protocol
    payload=$(echo $1 | sed -e s,$protocol,,g)

    query=$(echo "$payload" | sed 's,^.*?,,')

    # extract the GET params from the query string
    # get params are in the form of key=value
    # concatenated with &
    declare -A params
    for param in $(echo "$query" | tr '&' '\n'); do
        key=$(echo "$param" | cut -f1 -d=)
        value=$(echo "$param" | cut -f2 -d=)
        params["$key"]="$value"
    done

    # extract title, uri, category and tags from the params
    title="${params['title']}"
    uri="${params['uri']}"
    category="${params['category']}"
    tags="${params['tags']}"
    # check if the tags are enclosed in square brackets
    if [[ $tags == \[*\] ]]; then
        # remove the square brackets from the tags
        tags="${tags:1:${#tags}-2}"
    fi

    BOOKMARKS_INSTALL_DIR=/usr/local/bash-bookmarks
    gnome-terminal -- /bin/bash -c "$BOOKMARKS_INSTALL_DIR/bookmarks add --title \"$title\" --uri \"$uri\" --category \"$category\" --tags \"$tags\"; exec /bin/bash"
fi
